spring:
  dubbo:
    application:
      name: baochunyu-consumer
    registry:
      address: zookeeper://192.168.235.128:2181
    protocol:
      name: dubbo
      port: 20881

server:
  port: 9999
#spring:
#  dubbo:
#    app: dubbo-uic-consumer
#    registry: zookeeper://192.168.235.128:2181
#    protocol: dubbo